[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
zkevm = "${ZKEVM_RPC_URL}"
optimism-goerli = "${OPTIMISM_GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
optimism-goerli = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
